advection:
  scheme: sl
boundary_conditions:
  top_wall:
    type: neumann
compute:
  device: auto
domain:
  Lx: 10.68
  Ly: 3.2
  Lz: 1.0
  stretching_type: bottom
flow:
  Re: 2870.0
  Re_tau: 180.0
  U_bulk: 1.0
  gamma: 1.8
grid:
  nx: 256
  ny: 256
  nz: 100
initialization:
  field_file: results_180cans_sl_noextrap/fields_final.npz
  reset_time: false
  type: file
output:
  n_out: 200
  n_save: 1000000000
  n_snapshot: 30
  results_folder: results_180cans_sl_burst
sl:
  interp_dtype: fp32_accum64
  interp_order: 4
  n_traj_iters: 2
  time_scheme: v2
  traj_extrapolation: none
  traj_interp_order: 2
solver:
  type: fft
statistics:
  enabled: false
  n_stats: 3
  output_file: turbulence_stats.npz
  state_file: turbulence_stats_state.npz
  t_stats: 5.0
  z_plus_target: 15.0
time:
  CFL_target: 3.0
  dt: 0.005
  dt_max: 0.034
  dt_min: 0.0001
  dt_update_interval: 10
  n_steps: 2000000000
  scheme: IMEX
  t_max: 60.0
