advection:
  scheme: sl
compute:
  device: auto
domain:
  Lx: 15.707
  Ly: 6.282
  Lz: 2.0
flow:
  Re: 10000.0
  Re_tau: 550.0
  U_bulk: 1.0
  gamma: 2.6
grid:
  nx: 768
  ny: 768
  nz: 180
initialization:
  field_file: /home/giorgio/torChannel/results_big_550_stats/fields.npz
  reset_time: true
  type: vortices
output:
  n_out: 50
  n_save: 2000
  results_folder: results_550_sl_ab
sl:
  interp_dtype: fp64
  interp_order: 4
  n_traj_iters: 2
  traj_interp_order: 2
solver:
  type: fft
statistics:
  enabled: true
  n_stats: 20
  output_file: turbulence_stats.npz
  state_file: turbulence_stats_state.npz
  t_stats: 5.0
  z_plus_target: 15.0
time:
  CFL_target: 3.0
  dt: 0.01
  dt_max: 0.013
  dt_min: 0.0005
  dt_update_interval: 10
  n_steps: 2000000000
  scheme: IMEX
  t_max: 50.0
