advection:
  scheme: eulerian
compute:
  device: auto
domain:
  Lx: 12.566370614
  Ly: 4.188790205
  Lz: 2.0
flow:
  Re: 5600.0
  Re_tau: 180.0
  U_bulk: 1.0
  gamma: 1.8
grid:
  nx: 192
  ny: 160
  nz: 128
initialization:
  n_vortices: 4
  perturbation_intensity: 0.08
  type: vortices
output:
  n_out: 50
  n_save: 2000
  results_folder: results_180_ref
sl:
  interp_dtype: fp64
  interp_order: 4
  n_traj_iters: 2
  traj_interp_order: 2
solver:
  type: fft
statistics:
  enabled: true
  n_stats: 200
  output_file: turbulence_stats.npz
  state_file: turbulence_stats_state.npz
  t_stats: 100.0
  z_plus_target: 15.0
time:
  CFL_target: 0.28
  dt: 0.01
  dt_max: 0.02
  dt_min: 0.0005
  dt_update_interval: 10
  n_steps: 2000000000
  scheme: IMEX
  t_max: 300.0
