advection:
  scheme: sl
boundary_conditions:
  top_wall:
    type: neumann
compute:
  device: auto
domain:
  Lx: 7.7772
  Ly: 3.2405
  Lz: 1.0
  stretching_type: bottom
flow:
  Re: 6900.0
  Re_tau: 395.0
  U_bulk: 1.0
  gamma: 2.1
grid:
  nx: 384
  ny: 256
  nz: 100
initialization:
  field_file: data/fields_re395_seed.npz
  reset_time: true
  type: interpolate
output:
  n_out: 50
  n_save: 5000
  results_folder: results/re395_sl_dt020
  t_snapshot: 10.0
sl:
  bdf2_pressure: noninc
  interp_dtype: fp32_accum64
  interp_order: 6
  n_traj_iters: 2
  traj_interp_order: 2
solver:
  type: fft
statistics:
  enabled: true
  n_stats: 10
  output_file: turbulence_stats.npz
  state_file: turbulence_stats_state.npz
  t_stats: 30.0
  z_plus_target: 15.0
time:
  CFL_target: 3.0
  dt: 0.002
  dt_max: 0.0088
  dt_min: 0.0001
  dt_update_interval: 10
  n_steps: 2000000000
  scheme: IMEX
  t_max: 100.0
